### ISSUE TITLE
Brainvisa 5.3 : Compilation error - documentation

### ISSUE THREAD

**Issue by PierreAuriau** [brainvisa/brainvisa.github.io#138]
**Describe the bug**
During the installation of Brainvisa for developpers, the compilation with the command `bv_maker` failed with an error which seems to be linked to the documentation. I tried the distro brainvisa and open-source with the master branch.

**To Reproduce**
Steps to reproduce the behaviour:
1. Installation of Brainvisa with the singularity image
2. Compilation with `bv_maker` command
3. Compilation stopped with the error below :

```
make[1]: *** [CMakeFiles/Makefile2:5413: CMakeFiles/doc.dir/rule] Error 2
make: *** [Makefile:303: doc] Error 2
Traceback (most recent call last):
  File "/casa/host/bootstrap/brainvisa-cmake/python/brainvisa/maker/commands.py", line 71, in process
    logs = getattr(o, method)(*meth_args,
  File "/casa/host/bootstrap/brainvisa-cmake/python/brainvisa/maker/build.py", line 703, in doc
    system(cwd=self.directory, *
  File "/casa/host/bootstrap/brainvisa-cmake/python/brainvisa/maker/subprocess.py", line 59, in system
    six.reraise(*error)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/casa/host/bootstrap/brainvisa-cmake/python/brainvisa/maker/subprocess.py", line 48, in system
    raise OSError()
OSError: Command failed: 'make' '-j32' 'doc'
```

**Environment:**
 - Engine: Singularity 
 - Version of BrainVISA : 5.3 / master  branch
 - For local builds, version of the casa-dev image: casa-dev-5.3-19

Thank you for your help !

**Comment by denisri** [comment]
Hi,
unfortunately the build log is not complete here. Especially in parallel builds like here (32 build processes are used in parallel in your case) the "real" error may happen some time before the last build process ends, and the message may be lost in the very verbose outputs.
Can you run in the container:
```
cd /casa/host/build
make doc
```
then the error should be at the end.

**Comment by PierreAuriau** [comment]
Thank you for your answer. The `make doc` command gives this error : 
```
Reading FGraph version 3.0o_examples... [ 78%] anagraphannotate.py                                                          
Warning: wrong filename_base in graph, trying to fix it
Segmentation fault (core dumped)
make[3]: *** [build_files/anatomist-gpl/pyanatomist/CMakeFiles/anatomist-gpl-sphinx.dir/build.make:71: build_files/anatomist-gpl/pyanatomist/CMakeFiles/anatomist-gpl-sphinx] Error 139
make[2]: *** [CMakeFiles/Makefile2:26790: build_files/anatomist-gpl/pyanatomist/CMakeFiles/anatomist-gpl-sphinx.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:5413: CMakeFiles/doc.dir/rule] Error 2
make: *** [Makefile:303: doc] Error 2
```

Just before the error, I also got this warning : 
```
WARNING: /casa/host/src/anatomist/anatomist-gpl/master/pyanatomist/doc/examples/graph_building.py failed to execute correctly: Traceback (most recent call last):
  File "/casa/host/src/anatomist/anatomist-gpl/master/pyanatomist/doc/examples/graph_building.py", line 50, in <module>
    graph = aims.Graph('RoiArg')
  File "/casa/host/build/python/soma/aims/__init__.py", line 1547, in genobj__new__
    return carto.GenericObject.__oldnew__(cls, *args, **kwargs)
TypeError: soma.aims.aimssip.Graph represents a C++ abstract class and cannot be instantiated
```

**Comment by denisri** [comment]
I have fixed the Graph problem. Could you try again please ?

**Comment by PierreAuriau** [comment]
I still have the same issue. I tried to re-install from scratch to ensure making any mistakes but the error remained.

**Comment by denisri** [comment]
Oh, you're right. I should not do so many things at the same time. I'm trying again...

**Comment by denisri** [comment]
I have pushed another fix. Could you try again please ?

**Comment by PierreAuriau** [comment]
All went well, thank you very much!
